const productData = [
    {
        name:"PREDATOR LEAGUE",
        price:"$29.99",
        image:"/public/images/adidas-shoes-2.png",
    },
    {
        name:"ADIDAS LEAGUE",
        price:"$39.99",
        image:"/public/images/adidas-shoes-11.png",
    },
    {
        name:"REAL MADRID",
        price:"$129.99",
        image:"/public/images/real.webp",
    },
    {
        name:"NIKE T-SHIRT",
        price:"$15.99",
        image:"/public/images/nike-shirt.png",
    },
    {
        name:"academy-football",
        price:"$45.99",
        image:"/public/images/academy-football-1.png",
    },
    {
        name:"academy-football",
        price:"$77.99",
        image:"/public/images/academy-football-2_prev_ui.png",
    },
    {
        name:"academy-football",
        price:"$66.99",
        image:"/public/images/academy-football-3_prev_ui.png",
    },
    {
        name:"atletico-madrid",
        price:"$109.99",
        image:"/public/images/atletico-madrid_prev_ui.png",
    },
    {
        name:"brooklyn",
        price:"$200.99",
        image:"/public/images/brooklyn_prev_ui.png",
    },
    {
        name:"chicago-bulls",
        price:"$240.99",
        image:"/public/images/chicago-bulls_prev_ui.png",
    },
    {
        name:"custom-mercurial",
        price:"$98.99",
        image:"/public/images/custom-mercurial-vapor-15_prev_ui.png",
    },
    {
        name:"dri-fit-club",
        price:"$14.99",
        image:"/public/images/dri-fit-club_prev_ui.png",
    },
    {
        name:"dri-fit-fly",
        price:"$29.99",
        image:"/public/images/dri-fit-fly_prev_ui.png",
    },
    {
        name:"everyday-playground",
        price:"$49.99",
        image:"/public/images/everyday-playground_prev_ui.png",
    },
    {
        name:"jordan-playground",
        price:"$59.99",
        image:"/public/images/jordan-playground-1_prev_ui.png",
    },
    {
        name:"liverpool-fc",
        price:"$134.99",
        image:"/public/images/liverpool-fc_prev_ui.png",
    },
    {
        name:"los-angeles",
        price:"$269.99",
        image:"/public/images/los-angeles_prev_ui.png",
    },
    {
        name:"mercurial-vapor-15",
        price:"$409.99",
        image:"/public/images/mercurial-vapor-15_prev_ui.png",
    },
    {
        name:"phantom-gx-2",
        price:"$275.99",
        image:"/public/images/phantom-gx-2_prev_ui.png",
    },
    {
        name:"phantom-luna-2",
        price:"$322.99",
        image:"/public/images/phantom-luna-2_prev_ui.png",
    },
]

export default productData